package app_error

const (
	ERR_RECORD_NOT_FOUND = "ERR_RECORD_NOT_FOUND"
	ERR_INTERNAL_SERVER  = "ERR_INTERNAL_SERVER"
	ERR_INVALID_REQUEST  = "ERR_INVALID_REQUEST"
	ERR_DB_QUERY         = "ERR_DB_QUERY"
)
